name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
  print:
    runs-on: ubuntu-latest

    steps:
      - name: print message
        run:: echo "Hello this my pipeline"
