name: Build-Store-DeployNonProd-Testing

on:
  push:
    branches:
      - UAT


jobs: #job will running parallely
  build: #this is job name, can change it
    runs-on: ubuntu-latest #this is node agent

    steps: #steps will run sequentially
      - name: Checkout Repository
        uses: actions/checkout

      - name: Build package
        run: echo "Building package"
        
      - name: Store
        run: echo "Store into artifactory"

      - name: Deploy
        run: echo "Deploy to non prod environment"

      - name: Testing
        run: echo "Running functional testing"

  #      - name: Set up Node.js
  #        uses: actions/setup-node@v3
  #        with:
  #          node-version: "14"

  #- name: Install Dependencies
  # run: npm install

  #- name: Build
  # run: npm run build

  #- name: Test
  # run: npm test
  #tse
  test:
    runs-on: ubuntu-latest

    steps:
      - name: testing
        run: echo "Hello there, I am doing testing here!!!"

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: deploy
        run: echo "Deployment successfully"
